#include <algorithm>
#include <cassert>
#include <fstream>
#include <filesystem>
#include <iostream>
#include <iterator>
#include <map>
#include <mutex>
#include <string>
#include <sstream>
#include <thread>
#include <vector>
#include <errno.h>
#include <fcntl.h>
#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <android/log.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/sendfile.h>
#include <sys/stat.h>
